/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_notzed_jjmpeg_AVStream */

#ifndef _Included_au_notzed_jjmpeg_AVStream
#define _Included_au_notzed_jjmpeg_AVStream
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
