/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_notzed_jjmpeg_AVCodecContext */

#ifndef _Included_au_notzed_jjmpeg_AVCodecContext
#define _Included_au_notzed_jjmpeg_AVCodecContext
#ifdef __cplusplus
extern "C" {
#endif
#undef au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_UNKNOWN
#define au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_UNKNOWN -1L
#undef au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_VIDEO
#define au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_VIDEO 0L
#undef au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_AUDIO
#define au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_AUDIO 1L
#undef au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_DATA
#define au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_DATA 2L
#undef au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_SUBTITLE
#define au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_SUBTITLE 3L
#undef au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_ATTACHMENT
#define au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_ATTACHMENT 4L
#undef au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_NB
#define au_notzed_jjmpeg_AVCodecContext_AVMEDIA_TYPE_NB 5L
/*
 * Class:     au_notzed_jjmpeg_AVCodecContext
 * Method:    open
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_au_notzed_jjmpeg_AVCodecContext_open
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     au_notzed_jjmpeg_AVCodecContext
 * Method:    decode_video
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_au_notzed_jjmpeg_AVCodecContext_decode_1video
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     au_notzed_jjmpeg_AVCodecContext
 * Method:    register_all
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_au_notzed_jjmpeg_AVCodecContext_register_1all
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
