/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_notzed_jjmpeg_AVPacket */

#ifndef _Included_au_notzed_jjmpeg_AVPacket
#define _Included_au_notzed_jjmpeg_AVPacket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     au_notzed_jjmpeg_AVPacket
 * Method:    get_data
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_au_notzed_jjmpeg_AVPacket_get_1data
  (JNIEnv *, jobject, jobject);

/*
 * Class:     au_notzed_jjmpeg_AVPacket
 * Method:    free_packet
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_au_notzed_jjmpeg_AVPacket_free_1packet
  (JNIEnv *, jobject, jobject);

/*
 * Class:     au_notzed_jjmpeg_AVPacket
 * Method:    allocate
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_au_notzed_jjmpeg_AVPacket_allocate
  (JNIEnv *, jclass);

/*
 * Class:     au_notzed_jjmpeg_AVPacket
 * Method:    free
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_au_notzed_jjmpeg_AVPacket_free
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
