/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_notzed_jjmpeg_AVFormatContext */

#ifndef _Included_au_notzed_jjmpeg_AVFormatContext
#define _Included_au_notzed_jjmpeg_AVFormatContext
#ifdef __cplusplus
extern "C" {
#endif
#undef au_notzed_jjmpeg_AVFormatContext_AVSEEK_FLAG_BACKWARD
#define au_notzed_jjmpeg_AVFormatContext_AVSEEK_FLAG_BACKWARD 1L
#undef au_notzed_jjmpeg_AVFormatContext_AVSEEK_FLAG_BYTE
#define au_notzed_jjmpeg_AVFormatContext_AVSEEK_FLAG_BYTE 2L
#undef au_notzed_jjmpeg_AVFormatContext_AVSEEK_FLAG_ANY
#define au_notzed_jjmpeg_AVFormatContext_AVSEEK_FLAG_ANY 4L
#undef au_notzed_jjmpeg_AVFormatContext_AVSEEK_FLAG_FRAME
#define au_notzed_jjmpeg_AVFormatContext_AVSEEK_FLAG_FRAME 8L
/*
 * Class:     au_notzed_jjmpeg_AVFormatContext
 * Method:    open_input_file
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_au_notzed_jjmpeg_AVFormatContext_open_1input_1file
  (JNIEnv *, jclass, jstring, jobject, jint, jobject, jobject);

/*
 * Class:     au_notzed_jjmpeg_AVFormatContext
 * Method:    close_input_file
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_au_notzed_jjmpeg_AVFormatContext_close_1input_1file
  (JNIEnv *, jobject, jobject);

/*
 * Class:     au_notzed_jjmpeg_AVFormatContext
 * Method:    seek_frame
 * Signature: (Ljava/nio/ByteBuffer;IJI)I
 */
JNIEXPORT jint JNICALL Java_au_notzed_jjmpeg_AVFormatContext_seek_1frame
  (JNIEnv *, jobject, jobject, jint, jlong, jint);

/*
 * Class:     au_notzed_jjmpeg_AVFormatContext
 * Method:    find_stream_info
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_au_notzed_jjmpeg_AVFormatContext_find_1stream_1info
  (JNIEnv *, jobject, jobject);

/*
 * Class:     au_notzed_jjmpeg_AVFormatContext
 * Method:    read_frame
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_au_notzed_jjmpeg_AVFormatContext_read_1frame
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
