/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_notzed_jjmpeg_AVNative */

#ifndef _Included_au_notzed_jjmpeg_AVNative
#define _Included_au_notzed_jjmpeg_AVNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     au_notzed_jjmpeg_AVNative
 * Method:    getPointer
 * Signature: (Ljava/nio/ByteBuffer;II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_au_notzed_jjmpeg_AVNative_getPointer
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     au_notzed_jjmpeg_AVNative
 * Method:    getPointerIndex
 * Signature: (Ljava/nio/ByteBuffer;III)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_au_notzed_jjmpeg_AVNative_getPointerIndex
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     au_notzed_jjmpeg_AVNative
 * Method:    getPointerBits
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_au_notzed_jjmpeg_AVNative_getPointerBits
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
