/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_notzed_jjmpeg_AVCodec */

#ifndef _Included_au_notzed_jjmpeg_AVCodec
#define _Included_au_notzed_jjmpeg_AVCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     au_notzed_jjmpeg_AVCodec
 * Method:    find_encoder
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_au_notzed_jjmpeg_AVCodec_find_1encoder
  (JNIEnv *, jclass, jint);

/*
 * Class:     au_notzed_jjmpeg_AVCodec
 * Method:    find_decoder
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_au_notzed_jjmpeg_AVCodec_find_1decoder
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
