/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_notzed_jjmpeg_AVFrame */

#ifndef _Included_au_notzed_jjmpeg_AVFrame
#define _Included_au_notzed_jjmpeg_AVFrame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     au_notzed_jjmpeg_AVFrame
 * Method:    alloc_frame
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_au_notzed_jjmpeg_AVFrame_alloc_1frame
  (JNIEnv *, jclass);

/*
 * Class:     au_notzed_jjmpeg_AVFrame
 * Method:    free_frame
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_au_notzed_jjmpeg_AVFrame_free_1frame
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
